language: java

jdk:
 - openjdk7

before_install: 
 - sudo apt-get update -qq
 - git clone https://github.com/csgf/grid-and-cloud-engine.git -b FutureGateway 

# Building the grid and Cloud engine
install:
 - cd grid-and-cloud-engine
 - cd grid-and-cloud-engine-threadpool
 - mvn install dependency:copy-dependencies
 - cd ../grid-and-cloud-engine_M
 - mvn install dependency:copy-dependencies

notifications:
  email:
    recipients:
        - riccardo.bruno@ct.infn.it
        - mario.torrisi@ct.infn.it
