language: java

jdk:
 - openjdk7

before_install: 
 - sudo apt-get update -qq

 - mkdir GridEngine
 - cd GridEngine
 - mkdir src
 - mv ../it/ ./src
 - rm -rf src/it/infn/ct/ThreadPool/
 - rm -rf src/it/infn/ct/GridEngine/Data
 - cp ../build.xml .

# Install dependencies
 - wget http://grid.ct.infn.it/csgf/binaries/GridEngine_v1.5.10.zip
 - unzip GridEngine_v1.5.10.zip 

# Building the grid and Cloud engine
install:
 - ant build

notifications:
  email:
    recipients:
        - mario.torrisi@ct.infn.it
